[workspace]
members = [
    "event-sauce",
    "event-sauce-derive",
    "storage-sqlx"
]

[patch.crates-io]
event-sauce = { path = "event-sauce" }
event-sauce-derive = { path = "event-sauce-derive" }
event-sauce-storage-sqlx = { path = "storage-sqlx" }
