version: "3.2"
services:
  postgres:
    image: "postgres:11-alpine"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: sauce
      POSTGRES_USER: sauce
      POSTGRES_PASSWORD: sauce
    volumes:
      - "./postgres_initdb:/docker-entrypoint-initdb.d:ro"
    networks:
      - postgres

  adminer:
    image: "adminer:4.7"
    ports:
      - "8081:8080"
    networks:
      - postgres

networks:
  postgres:
