# Check that everything (tests, benches, etc) builds in std environments
precheck_steps: &precheck_steps
  docker:
    - image: circleci/rust:1.42.0
    - image: postgres:11-alpine
      environment:
        POSTGRES_USER: sauce
        POSTGRES_PASSWORD: sauce
        POSTGRES_DB: sauce
  steps:
    - checkout
    - restore_cache:
        key: v2-event-sauce-{{ .Environment.CIRCLE_JOB }}-{{ checksum "event-sauce/Cargo.toml" }}-{{ checksum "event-sauce-derive/Cargo.toml" }}
    - run: rustup self update
    - run: cargo update
    - run: sudo apt install -qq linkchecker
    - run: rustup default ${RUST_VERSION:-stable}
    - run: cargo install cargo-readme
    - run: rustup component add rustfmt
    - run: rustup toolchain add nightly
    - run: ./build.sh
    - save_cache:
        key: v2-event-sauce-{{ .Environment.CIRCLE_JOB }}-{{ checksum "event-sauce/Cargo.toml" }}-{{ checksum "event-sauce-derive/Cargo.toml" }}
        paths:
          - ./target
          - /usr/local/cargo/registry

version: 2
jobs:
  precheck-stable:
    <<: *precheck_steps
  precheck-beta:
    environment:
      - RUST_VERSION: 'beta'
    <<: *precheck_steps

build_jobs: &build_jobs
  jobs:
    - precheck-stable
    - precheck-beta

workflows:
  version: 2
  build_all:
    <<: *build_jobs

  # Build every day
  nightly:
    <<: *build_jobs
    triggers:
      - schedule:
          cron: '0 0 * * *'
          filters:
            branches:
              only:
                - master
